version: '3.9'

services:
  user-grade:
    image: user-grade-service
    restart: always
    build:
      context: ./
      dockerfile: ./build/multistage.Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  nats-streaming:
    image: nats-streaming
    restart: always