version: '3.9'

services:
  user-grade-master:
    image: user-grade-master-service
    restart: always
    build:
      context: ./
      dockerfile: build/multistage-master.Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      CONFIG_PATH: /config/config-docker-master
      REPLICA_TYPE: master

  user-grade-slave:
    image: user-grade-slave-service
    restart: always
    build:
      context: ./
      dockerfile: build/multistage-slave.Dockerfile
    ports:
      - "8082:8082"
      - "8083:8083"
    environment:
      CONFIG_PATH: /config/config-docker-slave
      REPLICA_TYPE: slave
      MASTER_BACKUP_ADDRESS: "http://user-grade-master:8081/backup"
    depends_on:
      - user-grade-master

  nats-streaming:
    image: nats-streaming
    restart: always